env:
  browser: true
  es6: true
  jest: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:flowtype/recommended'
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/flowtype'
  - 'prettier/react'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - flowtype
  - prettier
  - react
rules:
  no-console:
    - warn
  no-unused-vars:
    - error
    - argsIgnorePattern: "helperAPI|taskAPI|dirname"
  prettier/prettier:
    - error
    - trailingComma: all
  react/no-find-dom-node:
    - warn
